wandb: Starting wandb agent üïµÔ∏è
2021-11-02 10:37:43,324 - wandb.wandb_agent - INFO - Running runs: []
2021-11-02 10:37:43,618 - wandb.wandb_agent - INFO - Agent received command: run
2021-11-02 10:37:43,618 - wandb.wandb_agent - INFO - Agent starting run with config:
	ac_update_ratio: 4
	confidence_scale: 8.081417789167356
	target_entropy: 1.059789957065575
	use_entropy: False
2021-11-02 10:37:43,624 - wandb.wandb_agent - INFO - About to run command: python3 src/main.py --train --wandb
2021-11-02 10:37:48,635 - wandb.wandb_agent - INFO - Running runs: ['yzpsc5dl']
wandb: Currently logged in as: jjshoots (use `wandb login --relogin` to force relogin)
wandb: WARNING Ignored wandb.init() arg project when running a sweep
wandb: WARNING Ignored wandb.init() arg entity when running a sweep
-----------------------
Using Device cuda:0
-----------------------
wandb: wandb version 0.12.6 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.0
wandb: Syncing run 51365
wandb:  View project at https://wandb.ai/jjshoots/UA3SAC_gym
wandb:  View sweep at https://wandb.ai/jjshoots/UA3SAC_gym/sweeps/nktx8eqi
wandb:  View run at https://wandb.ai/jjshoots/UA3SAC_gym/runs/yzpsc5dl
wandb: Run data is saved locally in /home/taij/e2sac/wandb/run-20211102_103749-yzpsc5dl
wandb: Run `wandb offline` to turn off syncing.
wandb: Network error (ReadTimeout), entering retry loop.
/home/taij/.conda/envs/robocar/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
[34m[1mwandb[0m: Network error resolved after 0:00:38.553772, resuming normal operation.
XIO:  fatal IO error 0 (Success) on X server ":99"
      after 590 requests (590 known processed) with 3 events remaining.
2021-11-03 14:32:53,383 - wandb.wandb_agent - INFO - Cleaning up finished run: yzpsc5dl
wandb: Terminating and syncing runs. Press ctrl-c to kill.
/usr/bin/xvfb-run: line 186: kill: (373045) - No such process
/home/taij/.conda/envs/robocar/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
